--- name:thun_01_a_left
config:
  meta_filename: 'meta.yaml'
  in_image_size:
    width: 1440
    height: 1080
  in_events_frame_size:
    width: 640
    height: 480
  out_image_size:
    width: 640
    height: 480
  root_folder: '/media/javi/JAVIS/datasets/dsec/thun_01_a/'
  output_folder: '/media/javi/JAVIS/datasets/dsec/thun_01_a/'
  images_folder: 'images/left'
  disparity_events_folder: 'disparity/event'
  disparity_images_folder: 'disparity/image'
  img_ts_filename: 'images/timestamps.txt'
  events_filename: 'events/left/events.h5'
  imu_filename: 'imu_sync/left/imu.h5'
  disparity_ts_filename: 'disparity/timestamp.txt'

